---
- hosts: all
  name: Server setup
  vars_files:
    - ../variables.yml
    - ../.ansible.yml
  remote_user: "{{ login }}"
  become: yes

  tasks:
    - name: Update all packages
      zypper:
        name: "*"
        state: latest

    - name: Check if a reboot is needed
      register: linux_reboot_required_file
      stat: path=/boot/do_purge_kernels get_md5=no

    - name: Optional reboot
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: linux_reboot_required_file.stat.exists

    - name: Install Git
      zypper:
        name: git
        state: present

    - name: Install OpenJDK
      zypper:
        name: java-1_8_0-openjdk-devel
        state: present

    - name: Install Maven
      zypper:
        name: maven
        state: present

    - name: Create target directory
      file:
        path: "{{ project_root }}"
        state: directory

    - name: Create link to app executable
      file:
        src: "{{ project_src }}/target/{{ project_name }}.jar"
        dest: "{{ project_root }}/app"
        state: link
        force: yes

    - name: Create service file
      copy:
        dest: "/usr/lib/systemd/system/{{ project_name }}.service"
        # nohup java -jar *.jar &
        content: |
          [Unit]
          Description=eSchool server
          Wants=basic.target
          After=basic.target network.target
          StartLimitIntervalSec=0

          [Install]
          WantedBy=multi-user.target
          Alias=eschool.service

          [Service]
          Type=simple
          Restart=always
          RestartSec=1s
          ExecStart=/usr/bin/java -jar {{ project_root }}/app

    - name: Reload systemctl daemon
      systemd:
        daemon_reload: yes
