---
- hosts: all
  name: Project setup
  gather_facts: no
  vars_files:
    - ../variables/.creds.yml
    - ../variables/.params.yml
    - ../variables/main.yml
  remote_user: "{{ vm_login }}"
  become: yes

  tasks:
    - name: Disable service
      systemd:
        name: "{{ project_name }}"
        enabled: no
        state: stopped

    - name: Clone private repo
      become: yes
      become_user: "{{ project_usergroup }}"
      git:
        repo: "{{ project_repo }}"
        dest: "{{ project_source }}"
        version: "{{ project_repo_branch }}"
        single_branch: yes
        key_file: "{{ deploy_key }}"
        accept_hostkey: yes
      environment:
        GIT_TERMINAL_PROMPT: 0

    - name: Build app
      become: yes
      become_user: "{{ project_usergroup }}"
      args:
        chdir: "{{ project_source }}"
      shell: source {{ env_file }} && mvn clean package

    - name: Enable service
      systemd:
        name: "{{ project_name }}"
        enabled: yes
        state: started
